#!/bin/sh

# Lets delete all test controllers after executing tests.

cat /proc/self/cgroup | grep -q zdtmtst.defaultroot || exit 0

uuid=$1

tdir=`mktemp -d zdtm.XXXXXX`
set -e
for i in "zdtmtst" "zdtmtst.defaultroot"; do
	mount -t cgroup -o none,name=$i zdtm $tdir
	# remove a fake group if exists
	if [ -d "$tdir/holder.$uuid" ]; then
		rmdir $tdir/holder.$uuid
	fi
	umount -l $tdir
done
rmdir $tdir
